databases:
  - name: journal_app
    databaseName: journal_app_0elv
    user: journal_app_0elv_user

services:
  - type: web
    name: stock-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: journal_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false